account/urls.py
from django.urls import path, re_path
from account.views import (
    RegisterView,
    CustomLoginView,
    logout,

)

app_name = 'account'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', logout, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
 

]

tasks/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('', views.index, name="list"),
	path('update_task/<str:pk>/', views.updateTask, name="update_task"),
	path('delete/<str:pk>/', views.deleteTask, name="delete"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('accounts/', include('account.urls', namespace='account')),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import  password_validation
from django import forms
# from django.contrib.auth import get_user_model
from django.utils.translation import gettext, gettext_lazy as _
# from django.contrib.auth.forms import UserCreationForm, UsernameField, AuthenticationForm

# User = get_user_model()

class User(AbstractUser):
    email = models.EmailField(_('email'), unique=True,)
    phone = models.CharField(max_length=50, null=True,blank=True)

tasks/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Task(models.Model):
    
    title=models.CharField('title', max_length=255)
    complete= models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Task")
        verbose_name_plural = ("Tasks")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("Task_detail", kwargs={"pk": self.pk})

account/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth import  get_user_model,password_validation
from django.contrib import messages
from django.contrib.auth import get_user_model, password_validation
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth.forms import (
    UserCreationForm, UsernameField, AuthenticationForm, PasswordResetForm, SetPasswordForm
)

User = get_user_model()


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'Password'
            }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'Confirm Password'
            }),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = (
            'username',
            'email', 
            'password1',
            'password2', 

        )
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Email'
            }),
        }


    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('Confirm password is not same with password')
        return password2

    def _post_clean(self):
        super()._post_clean()
        password1 = self.cleaned_data.get('password1')
        try:
            password_validation.validate_password(password1, self.instance)
        except forms.ValidationError as error:
            self.add_error('password1', error)
        return password1





class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True,
                                                           'class': 'form-control',
                                                           'placeholder': 'Username'
                                                           }))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password'
        }),
    )

tasks/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from .models import *
from django.forms.fields import CharField

class TaskForm(forms.ModelForm):
    title = CharField(widget=forms.TextInput(attrs={'autofocus': True,
                                                            'class': 'form-control',
                                                            'placeholder': 'Enter your task here'
                                                            }))
 
    
    class Meta:
        model=Task
        fields='__all__'
    

account/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.encoding import force_text
from django.contrib.auth import get_user_model
from account.forms import RegistrationForm, LoginForm
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from account.models import User
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView
from account.forms import RegistrationForm, LoginForm

User = get_user_model()




class RegisterView(CreateView):
    form_class = RegistrationForm
    template_name = 'register.html'
    success_url = reverse_lazy('account:login')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('http://127.0.0.1:8000/')
        return super(RegisterView, self).dispatch(request, *args, **kwargs)



class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = 'login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('http://127.0.0.1:8000/')
        return super(CustomLoginView, self).dispatch(request, *args, **kwargs)


def logout(request):
    django_logout(request)
    return redirect('/')

tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *




@login_required
def index(request):
	tasks = Task.objects.all()

	form = TaskForm()

	if request.method =='POST':
		form = TaskForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('/')


	context = {'tasks':tasks, 'form':form}
	return render(request, 'list.html', context)



def updateTask(request, pk):
	task = Task.objects.get(id=pk)

	form = TaskForm(instance=task)

	if request.method == 'POST':
		form = TaskForm(request.POST, instance=task)
		if form.is_valid():
			form.save()
			return redirect('/')

	context = {'form':form}

	return render(request, 'update_task.html', context)



def deleteTask(request, pk):
	item = Task.objects.get(id=pk)

	if request.method == 'POST':
		item.delete()
		return redirect('/')

	context = {'item':item}
	return render(request, 'delete.html', context)

account/templates/login.html
{% extends 'base.html'  %}


{% block content %}

      
      <!-- Content -->
      <div id="content"> 
        
        <!--======= PAGES INNER =========-->
        <section class="chart-page padding-top-100 padding-bottom-100">
          <div class="container"> 
            
            <!-- Payments Steps -->
            <div class="shopping-cart"> 
              
              <!-- SHOPPING INFORMATION -->
              <div class="cart-ship-info">
                <div class="row"> 
                  
                  <!-- ESTIMATE SHIPPING & TAX -->
                  <div class="col-sm-7">
                    <h6>LOGIN YOUR ACCOUNT</h6>
                    <form action="" method="POST" >
                     {% csrf_token %}
                      <ul class="row">
                        <li class="col-md-12">
                            {{form.non_field_errors}}
                            {% for field in form %}
                                <div class="form-group">
                                    {{field}}
                                    {{field.help_text}}
                                    {{field.errors}}
                                </div>
                            {% endfor  %} 
                            </li> 
                        <!-- LOGIN -->
                        <li class="col-md-4">
                        <br>
                          <button type="submit" class="btn">LOGIN</button>
                        </li>
                        

    
                      </ul>
                      <br>
                        <div class="form-group">
                                <a href="{% url 'account:register' %}" class="">Don't have an account? Sign up</a>
                        </div>
                    </form>
                   
                    
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {% endblock %}

account/templates/register.html
{% extends 'base.html'  %}


{% block content %}
    

     
  <!-- Content -->
  <div id="content"> 
    
    <!--======= PAGES INNER =========-->
    <section class="chart-page padding-top-100 padding-bottom-100">
      <div class="container"> 
        
        <!-- Payments Steps -->
        <div class="shopping-cart"> 
          
          <!-- SHOPPING INFORMATION -->
          <div class="cart-ship-info register">
            <div class="row"> 
              
              <!-- ESTIMATE SHIPPING & TAX -->
              <div class="col-sm-12">
                <h6>REGISTER</h6>
                <form action="" method="POST">
                {% csrf_token %}
                  <ul class="row">

                    <!-- USERNAME -->
                    <li class="col-md-6">
                      {{form.username}}
                      {%for error in form.username.errors%}
                        <li class="text-danger">{{error}}</li>
                      {%endfor%}
                    </li>

                 <!-- USERNAME -->
                 <li class="col-md-6">
                    {{form.email}}
                    {%for error in form.email.errors%}
                      <li class="text-danger">{{error}}</li>
                    {%endfor%}
                  </li>

                    
                    <!-- LAST NAME -->
                    <li class="col-md-6">
                      {{form.password1}}
                      {%for error in form.password1.errors%}
                        <li class="text-danger">{{error}}</li>
                        {%endfor%}
                    </li>
                    
                    <!-- LAST NAME -->
                    <li class="col-md-6">
                      {{form.password2}}
                      {%for error in form.password2.errors%}
                        <li class="text-danger">{{error}}</li>
                         {%endfor%}
                    </li>
                    
                    
                    <!-- SUBMIT -->
                    <li class="col-md-3">
                    <br>
                      <button type="submit" class="btn btn-primary">REGISTER NOW</button>
                    </li>
                  </ul>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    {% endblock %}

tasks/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description"
        content="This is to do list implemented using Django by Dennis Ivy who is a full stack web developer.">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>To Do Items</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    
</head>

<body>

    <div class="container">
        {% block content %} {% endblock content %}
    </div>

</body>


</html>

tasks/templates/delete.html
{% extends 'base.html'  %}


{% block content %}

      
<p>Are you sure you want to delete "{{item}}"?</p>

<a href="{% url 'list' %}" >Cancel</a>

<form method="POST" action="">
	{% csrf_token %}
	<button type="submit" class="btn btn-danger btn-sm">Delete</button>
</form>
{% endblock %}

tasks/templates/list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



    
<title>To Do App</title>
</head>
<body>

<div class="container">
 
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <li class="nav-item">
      {% if user.is_authenticated %}
   <a class="navbar-brand" href="{% url 'account:logout' %}">Logout</a>
    {%endif%}
      </li>
    </ul>
    <span class="navbar-text">
      HELLO,  {{user.username}} !
    </span>
  </div>
</nav>
</div>

<div class="center-column">
       <ul class="row">
        <li class="col-md-9">
        <form method="POST" action="/">
            {% csrf_token %}
            {{form.title}}
        </li>
        <li class="col-md-3">
           <button class="btn btn-outline-success"  type="submit">Create Task</button>
        </li>
        </form>

       </ul>
    
        <div class="todo-list">
    
        {% for task in tasks %}
            <div class="item-row">
            <div style="float:right;">
           <a class="btn btn-sm btn-success" href="{% url 'update_task' task.id %}">Update</a>
                <a class="btn btn-sm btn-danger" href="{% url 'delete' task.id %}">Delete</a>
    </div>
                {% if task.complete == True %}
                <strike>{{task}}</strike>
                {% else %}
                <span>{{task}}</span>
                {% endif %}
            </div>
        {% endfor %}
        </div>
    </div>
</body>
</html>

tasks/templates/update_task.html
{% extends 'base.html'  %}


{% block content %}

      
    <h3>Update Task</h3>

    <form method="POST" action="">
        {% csrf_token %}
    
        {{form}}
        <button type="submit" class="btn btn-primary btn-sm">Update</button>
        
        
    </form>
{% endblock %}